port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: true
  allow_tcp_fallback: true
keys:
  devkey: SjhHHIUvnFKcZrODPlmaKvOUImzOjpWHxuuvyIYF
redis:
  address: redis:6379
turn:
  enabled: true
  udp_port: 3479
log_level: info
